name: Android CI

on:
  #push:
  #  branches: [ "main", "master" ]
  #pull_request:
  #  branches: [ "main", "master" ]
  workflow_dispatch: # Allows manual triggering from the UI
  
jobs:
  build:
    name: Build Android DEBUG App
    runs-on: ubuntu-latest

    steps:
      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android App
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: composeApp/build/outputs/apk/debug/composeApp-debug.apk

      - name: Upload to AutoBuild
        uses: softprops/action-gh-release@v2
        with:
          tag_name: automated
          name: "Automated Android DEBUG Build (${{ github.event.repository.updated_at }})"
          body: "Automated workflow triggered build from the latest main branch."
          draft: false
          prerelease: true
          files: composeApp/build/outputs/apk/debug/composeApp-debug.apk

          

